[package]
name = "void_builder"
version = "0.1.0"
authors = ["CraftedCart"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.1"

# Logging
log = "0.4"
env_logger = "0.7.1"
